#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        0
bspc config window_gap          2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

sxhkd &
picom --config $HOME/.config/picom/picom.conf &
feh --bg-fill $HOME/.config/background/3d-10032024.jpg &
polybar &